import appTexts from './appTexts.json';

export const {
  BUTTONS,
  FORM_LABELS,
  FORM_PLACEHOLDERS,
  VALIDATION_MESSAGES,
  GENDER_OPTIONS,
  COUNTRY_OPTIONS,
  PHONE_COUNTRY_CODES,
  OTP_VERIFICATION,
  TITLES,
  FOOTER,
  COMMON
} = appTexts;
